import json

entries = [
("injection, innoculation","allurà","n.f. (pl. allùrai)",20),
("syringe used for injection","allurà","n.f. (pl. allùrai)",20),
("pupil, student, learner, esp. of koranic school","almajìri","n.m. (f. almajìra, pl. almàjìrai)",20),
("destitute or poor person","almajìri","n.m. (f. almajìra, pl. almàjìrai)",20),
("scissors","almakàshi","n.m. (pl. almàkàsai)",20),
("fable, fantasy","almàra","n.f.",20),
("fiction writing or narration","almàra","n.f.",20),
("the messiah, jesus christ","Almàsihù","n.m.",20),
("extravagant person, spendthrift","almùbazzàri","n.m. (f. almùbazzàra, pl. almùbàzzàrai)",20),
("dusk","almurù","n.m.",20),
("nation, community, the people, the public","al'ummà","n.f. (pl. al'ùmmai, al'ummomi)",20),
("religious ablution","alwàla","n.f.",20),
("rash promise","alwashi","n.m.",20),
("vomiting, vomit","amai","n.m.",20),
("working lazily","amàja","n.f.",20),
("push-cart with two wheels","amalankè","n.m.",20),
("big, strong male camel","amalè","n.m.",20),
("trust, mutual trust, friendliness, peace","amanà","n.f.",20),
("treaty, alliance","amanà","n.f.",20),
("honesty, reliability","amanà","n.f.",20),
("bride","amarya","n.f. (pl. amàre)",20),
("anything new, esp. car or bicycle","amarya","n.f. (pl. amàre)",20),
("flood, flooding, overflowing","ambàliyà","n.f.",20),
("congestion (of people)","ambàliyà","n.f.",20),
("mention sth.","ambàta","v.t. (ci/ce) (vn. ambato)",20),
("envelope","ambulàn","n.m. (pl. ambuloli)",20),
("ambulance","ambulàn","n.m. (pl. ambuloli)",20),
("derive benefit from sth.","amfanà","v.t. (i/e)",20),
("be beneficial to s.o.","amfanà","v.t. (i/e)",20),
("may god bring good luck! (used in allah ya ~)","amfàna","v.t.",20),
("benefit","amfanà","v.i.",20),
("usefulness, advantage, profit","amfàni","n.m.",20),
("produce, product","amfàni","n.m.",20),
("amen, so be it","amin","excl.",20),
("trust","amincè","v.t. (with i.o. or dà)",20),
("agree on sth.","amincè","v.t. (with i.o. or dà)",20),
("trust, trustworthiness, reliability","aminci","n.m.",20),
("friendship","aminci","n.m.",20),
("trusted or reliable friend","amini","n.m. (f. aminiya, pl. aminai)",20),
("do or make sth. well","aminta","v.t.",20),
("trust","amintà","v.i. (with dà)",20),
("but, nevertheless","amma","conj.",20),
("sound (bell, drum, gun, etc.)","amo","n.m.",20),
("echo","amo","n.m.",20),
("dandruff, scalp disease","amosàni","n.m.",20),
("receive, accept sth.","amsa","v.t. (shi/she)",20),
("answer or reply to (call, greeting, question, etc.)","amsà","v.t.",20),
("agree, consent to sth.","amsà","v.t.",20),
("reply, response, answer","amsà","n.f. (pl. amsoshi)",20),
("echo","amsà-kuwwà","n.f.",20),
("loudspeaker","amsà-kuwwà","n.f.",20),
("refrain (in song)","amshi","n.m.",20),
("stretcher","amukù","n.m.",20),
("beehive","amyà","n.f. (pl. amyoyi)",20),
("they, one, it","an","impers. pro. (past tense subj.)",20),
("is that really possible!","anâ","excl.",20),
("they, one, it","anà","impers. pro. (cont. tense subj.)",20),
("shuttle of loom","andira","n.f.",20),
("anchor of ship","angà","n.f.",20),
("cotton fluff","angàlalà","n.f.",20),
("push","angàzà","v.t. (ji/je)",20),
("push onto or into","angaza","v.t.",20),
("bridegroom","angò","n.m. (pl. angwàye)",20),
("cotton seed","angùrya","n.f.",20),
("piles, haemorrhoids","angùrya","n.f.",20),
]

with open(r"C:\Users\Adamu\Desktop\Hausa AI\data\processed\newman_1977\ha_en_pairs_chunk2.jsonl", "a", encoding="utf-8") as f:
    for en, ha, ctx, pg in entries:
        obj = {"source_en": en, "target_ha": ha, "context": ctx, "provenance": "newman_1977", "page": pg}
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")

with open(r"C:\Users\Adamu\Desktop\Hausa AI\data\processed\newman_1977\progress_chunk2.txt", "a", encoding="utf-8") as f:
    f.write(f"page 20: {len(entries)} entries (anini continues on page 21)\n")

print("wrote", len(entries))
